// Generated by CoffeeScript 1.9.1
(function() {
  angular.module('app', []);

  angular.module('app').controller('MainCtrl', function($scope) {
    return $scope.message = 'Hello from AngularJS';
  });

}).call(this);
