// Generated by CoffeeScript 1.9.1
(function() {
  var app, express, mongoose, port;

  express = require('express');

  app = express();

  app.use(express["static"](__dirname + '/public/vendor'));

  app.use(express["static"](__dirname + '/../client'));

  mongoose = require('./db');

  app.get('/', function(req, res) {
    return res.sendFile(__dirname + '/index.html');
  });

  port = 4000;

  app.listen(port, function() {
    return console.log("Server started listening on port " + port);
  });

}).call(this);
